##Problem 1:

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [0]:
import pandas as pd

count = 0
for x in range(0,1000):
  if x % 5 == 0 or x % 3 == 0:
    count = count + x
print (count)

233168

##Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [0]:
x = 1
y = 2
z = 0
total = 0

while z <=4000000:
    z = y
    if z % 2 == 0:
        total += z
    z = x + y
    x = y
    y = z

print (total)

4613732

##Problem 3

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [0]:
from math import sqrt

sqrt(600851475143)

775146.0992245268

In [0]:
import math
import time

t0 = time.time()

for x in reversed(range(2,775147)):
  shrt_cut = math.floor(math.sqrt(x))
  if 600851475143%x==0 and all(x%y!=0 for y in range(2,1+shrt_cut)):
    print(x)
    break
t1 = time.time()
    


print(t1-t0)

6857
0.31571531295776367

##Problem 4

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 Ã— 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [0]:
word_lst = ['animal', 'panama', 'radar']

palindrome = []

for item in word_lst:
  if item[0] == item[-1]:
    palindrome.append(item)
    
print (palindrome)

['radar']

In [0]:
two_prods = []

range_a = range(100,1000)
range_b = range(100,1000)

for x in range_a:
  for y in range_b:
    product = (x * y)
    two_prods.append(product)
  

str_lst = [str(i) for i in two_prods]
# str_lst = str(two_prods)
# print (str_lst)

palindrom = []

for number  in str_lst:
  if number[0] == number [-1]:
    if number[1] == number [-2]:
       if number [2] == number [-3]:
          palindrom.append(number)
    
# print (str_lst)
print(palindrom[0])
print(len(palindrom))
print(palindrom)

num_lst = [int(i) for i in palindrom]

num_lst.sort()
print (num_lst[-1])

10201
2470

##Problem 5
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [0]:
sml_range = range (2,21)
numb_range = range (10, 1000000000)
numb = []

factor = []
count = 0

for y in numb_range:
  if all(y%x == 0 for x in sml_range):
    factor.append(y)

  
factor

[232792560, 465585120, 698377680, 931170240]

##Problem 6
The sum of the squares of the first ten natural numbers is,

12 + 22 + ... + 102 = 385
The square of the sum of the first ten natural numbers is,

(1 + 2 + ... + 10)2 = 552 = 3025
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 âˆ’ 385 = 2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [0]:
sum_sq = 0
total = 0

for x in range(1,11):
  sum_sq = sum_sq + (x ** 2)
  total = total + x
  sq_tot = total ** 2
  
print (sq_tot - sum_sq)

2640

##Problem 7
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

In [0]:
big_range = range(2,1000000)

primes = []

for x in big_range:
  if all (x%y!=0 for y in range(2,x)):
    primes.append(x)
  elif len(primes) == 10001:
    break
print (len(primes))  
print (primes[-1])

10001
104743

##Problem 8
The four adjacent digits in the 1000-digit number that have the greatest product are 9 Ã— 9 Ã— 8 Ã— 9 = 5832.

7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [0]:

number = str(7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450)

prod_lst = []

num_range = range(0,987)
        
for i in num_range:
  product = (int(number[i]) * int(number[i+1]) * int(number[i+2]) * int(number[i+3])*
             int(number[i+4]) * int(number[i+5]) * int(number[i+6]) * int(number[i+7])*
             int(number[i+8]) * int(number[i+9]) * int(number[i+10]) * int(number[i+11])*
             int(number[i+12]))
  prod_lst.append(product)
  i+=1


print (prod_lst)

prod_lst.sort(reverse = True)
print(prod_lst)

[5000940, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4199040, 4898880, 9797760, 9797760, 2177280, 13063680, 7257600, 25401600, 50803200, 71124480, 284497920, 568995840, 189665280, 158054400, 112896000, 84672000, 84672000, 381024000, 63504000, 114307200, 65318400, 146966400, 62985600, 62985600, 283435200, 566870400, 1020366720, 1632586752, 1632586752, 2040733440, 453496320, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 78382080, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 371589120, 2972712960, 1857945600, 2477260800, 1651507200, 412876800, 294912000, 221184000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 235146240, 167961600, 188956800, 104976000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 42865200, 342921600, 244944000, 244944000, 69984000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 812851200, 812851200, 270950400, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6270566400, 14108774400, 23514624000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3225600, 2419200, 604800, 967680, 2419200, 3628800, 3628800, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 677376, 225792, 28224, 4032, 12096, 72576, 145152, 145152, 290304, 373248, 1492992, 6718464, 6718464, 3359232, 2239488, 6718464, 20155392, 53747712, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13063680, 3265920, 26127360, 17418240, 27869184, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 424673280, 495452160, 495452160, 1114767360, 836075520, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2709504, 24385536, 27869184, 97542144, 219469824, 768144384, 987614208, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 630118440, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120960000, 96768000, 96768000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2016000, 1008000, 3024000, 10584000, 13230000, 9922500, 59535000, 107163000, 107163000, 428652000, 214326000, 1500282000, 2700507600, 3780710640, 8821658160, 7841473920, 4480842240, 5377010688, 1792336896, 2091059712, 929359872, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 313528320, 235146240, 313528320, 940584960, 376233984, 125411328, 55738368, 148635648, 148635648, 1189085184, 396361728, 509607936, 445906944, 222953472, 74317824, 37158912, 6193152, 9289728, 32514048, 40642560, 30481920, 76204800, 66679200, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 365783040, 261273600, 87091200, 62208000, 31104000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 258048000, 258048000, 309657600, 309657600, 495452160, 123863040, 123863040, 371589120, 743178240, 212336640, 297271296, 37158912, 32514048, 5419008, 3612672, 4214784, 4741632, 5334336, 10668672, 42674688, 28449792, 28449792, 28449792, 36578304, 73156608, 83607552, 167215104, 125411328, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 627056640, 78382080, 117573120, 39191040, 19595520, 9797760, 1959552, 1959552, 559872, 1119744, 279936, 1119744, 1866240, 1658880, 9953280, 1105920, 7741440, 30965760, 61931520, 371589120, 247726080, 619315200, 619315200, 928972800, 1161216000, 2090188800, 261273600, 87091200, 348364800, 248832000, 186624000, 186624000, 155520000, 77760000, 139968000, 69984000, 163296000, 195955200, 108864000, 435456000, 1088640000, 1632960000, 2612736000, 870912000, 1161216000, 928972800, 3715891200, 3715891200, 928972800, 265420800, 353894400, 566231040, 424673280, 84934656, 56623104, 14155776, 42467328, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 223948800, 199065600, 33177600, 33177600, 24883200, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2048385024, 1820786688, 910393344, 1170505728, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 462944160, 462944160, 132269760, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 208372500, 250047000, 150028200, 100018800, 66679200, 80015040, 102876480, 257191200, 171460800, 24494400, 97977600, 156764160, 44789760, 268738560, 313528320, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[23514624000, 14108774400, 8821658160, 7841473920, 6270566400, 5377010688, 4480842240, 3780710640, 3715891200, 3715891200, 2972712960, 2700507600, 2612736000, 2477260800, 2091059712, 2090188800, 2048385024, 2040733440, 1857945600, 1820786688, 1792336896, 1651507200, 1632960000, 1632586752, 1632586752, 1500282000, 1189085184, 1170505728, 1161216000, 1161216000, 1114767360, 1088640000, 1020366720, 987614208, 940584960, 929359872, 928972800, 928972800, 928972800, 910393344, 870912000, 836075520, 812851200, 812851200, 768144384, 743178240, 630118440, 627056640, 619315200, 619315200, 568995840, 566870400, 566231040, 509607936, 495452160, 495452160, 495452160, 462944160, 462944160, 453496320, 445906944, 435456000, 428652000, 424673280, 424673280, 412876800, 396361728, 381024000, 376233984, 371589120, 371589120, 371589120, 365783040, 353894400, 348364800, 342921600, 313528320, 313528320, 313528320, 309657600, 309657600, 297271296, 294912000, 284497920, 283435200, 270950400, 268738560, 265420800, 261273600, 261273600, 258048000, 258048000, 257191200, 250047000, 248832000, 247726080, 244944000, 244944000, 235146240, 235146240, 223948800, 222953472, 221184000, 219469824, 214326000, 212336640, 208372500, 199065600, 195955200, 189665280, 188956800, 186624000, 186624000, 171460800, 167961600, 167215104, 163296000, 158054400, 156764160, 155520000, 150028200, 148635648, 148635648, 146966400, 139968000, 132269760, 125411328, 125411328, 123863040, 123863040, 120960000, 117573120, 114307200, 112896000, 108864000, 107163000, 107163000, 104976000, 102876480, 100018800, 97977600, 97542144, 96768000, 96768000, 87091200, 87091200, 84934656, 84672000, 84672000, 83607552, 80015040, 78382080, 78382080, 77760000, 76204800, 74317824, 73156608, 71124480, 69984000, 69984000, 66679200, 66679200, 65318400, 63504000, 62985600, 62985600, 62208000, 61931520, 59535000, 56623104, 55738368, 53747712, 50803200, 44789760, 42865200, 42674688, 42467328, 40642560, 39191040, 37158912, 37158912, 36578304, 33177600, 33177600, 32514048, 32514048, 31104000, 30965760, 30481920, 28449792, 28449792, 28449792, 27869184, 27869184, 26127360, 25401600, 24883200, 24494400, 24385536, 20155392, 19595520, 17418240, 14155776, 13230000, 13063680, 13063680, 10668672, 10584000, 9953280, 9922500, 9797760, 9797760, 9797760, 9289728, 7741440, 7257600, 6718464, 6718464, 6718464, 6193152, 5419008, 5334336, 5000940, 4898880, 4741632, 4214784, 4199040, 3628800, 3628800, 3612672, 3359232, 3265920, 3225600, 3024000, 2709504, 2419200, 2419200, 2239488, 2177280, 2016000, 1959552, 1959552, 1866240, 1658880, 1492992, 1119744, 1119744, 1105920, 1008000, 967680, 677376, 604800, 559872, 373248, 290304, 279936, 225792, 145152, 145152, 72576, 28224, 12096, 4032, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

##Problem 9
A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

a^2 + b^2 = c^2
For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

In [0]:
import math
from math import sqrt
import time
import numpy as np

t0= time.time()
range_a = range(2,500)

perf_sq = [x**2 for x in range_a]


import itertools
for x,y,z in itertools.product(perf_sq, perf_sq, perf_sq):
  if x<y<z and x+y == z and  sqrt(x)+sqrt(y)+sqrt(z) == 1000:
    print('{},{},{}'.format(x,y,z))
    print('{},{},{}'.format(sqrt(x), sqrt(y), sqrt(z)))
    print(sqrt(x)*sqrt(y)*sqrt(z))
    break


t1 = time.time()

print(t1-t0)

40000,140625,180625
200.0,375.0,425.0
31875000.0
10.158155918121338

##Problem 10 
The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.

In [0]:
import math
import time

t0 = time.time()

big_range = range (2,2000000)
primes = 0


for x in big_range:
  shrt_cut = math.floor(math.sqrt(x))
  if all(x%y!=0 for y in range (2,1+shrt_cut)):
    primes = primes + x


t1 = time.time()

print ('Time:', t1-t0)
print(primes)

Time: 26.08341360092163
142913828922

##Project Euler Problem 11

In the 20Ã—20 grid below, four numbers along a diagonal line have been marked in red.

08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 99 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48

The product of these numbers is 26 Ã— 63 Ã— 78 Ã— 14 = 1788696.

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20Ã—20 grid?

In [0]:
num_string = ('08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00 81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65 52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91 22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80 24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50 32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70 67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21 24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72 21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95 78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92 16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57 86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58 19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40 04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66 88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69 04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36 20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16 20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54 01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48')
num_list = [int(i) for i in num_string.split()]


print(num_list[10[]]
i=4

hor = []
while i<=396:
      
  hor.append(num_list[(i-3)] * num_list[(i-2)] * num_list[(i-1)] * num_list[i])
  hor.append(num_list[(i-2)] * num_list[(i-1)] * num_list[i] * num_list[i+1])
  hor.append(num_list[(i-1)] * num_list[i] * num_list[i+1] * num_list[i+2])
  hor.append(num_list[i] * num_list[i+1] * num_list[i+2] * num_list[i+3])
  i+=1

#verticals
vert = []
i=61

while i <= 339:
  vert.append(num_list[(i-61)]*num_list[(i-41)]*num_list[(i-21)]*num_list[i])
  vert.append(num_list[(i-41)]*num_list[(i-21)]*num_list[i]*num_list[(i+21)])
  vert.append(num_list[(i-21)] * num_list[(i)] * num_list[(i+21)] * num_list[(i+41)])
  vert.append(num_list[(i)] * num_list[(i+21)] * num_list[(i+41)] + num_list[(i+61)])
  i+=1

#diagonals
diag = []
i=0

while i <=336:
  diag.append(num_list[(i)] * num_list[(i+21)] * num_list[i+42] + num_list[i+63])
  i+=1
  



#print(max(hor))

36

IndexError: ignored

In [0]:
num_string = ('08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00 81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65 52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91 22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80 24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50 32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70 67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21 24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72 21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95 78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92 16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57 86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58 19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40 04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66 88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69 04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36 20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16 20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54 01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48')
num_list = [int(i) for i in num_string.split()]

i=1
j=20
  

hor = []
while i < 18:
 
    hor.append(num_list[i-1]+num_list[i]+num_list[i+1]+num_list[i+2])
    hor.append(num_list[i*j]+num_list[(i*j)+1]+num_list[(i*j)+2]+num_list[(i*j)+3])
    i+=1
    j+=1
    print(hor)
#     if i==18:
#       i == 1
#       j +=3
   
# print(len(hor))
# print(17*20)

#remember to change to multiplication

[129, 237]
[129, 237, 159, 238]
[129, 237, 159, 238, 172, 146]
[129, 237, 159, 238, 172, 146, 150, 130]
[129, 237, 159, 238, 172, 146, 150, 130, 93, 239]
[129, 237, 159, 238, 172, 146, 150, 130, 93, 239, 55, 204]
[129, 237, 159, 238, 172, 146, 150, 130, 93, 239, 55, 204, 115, 107]
[129, 237, 159, 238, 172, 146, 150, 130, 93, 239, 55, 204, 115, 107, 119, 210]
[129, 237, 159, 238, 172, 146, 150, 130, 93, 239, 55, 204, 115, 107, 119, 210, 84, 183]
[129, 237, 159, 238, 172, 146, 150, 130, 93, 239, 55, 204, 115, 107, 119, 210, 84, 183, 91, 131]
[129, 237, 159, 238, 172, 146, 150, 130, 93, 239, 55, 204, 115, 107, 119, 210, 84, 183, 91, 131, 94, 144]
[129, 237, 159, 238, 172, 146, 150, 130, 93, 239, 55, 204, 115, 107, 119, 210, 84, 183, 91, 131, 94, 144, 142, 231]

IndexError: ignored

In [0]:
A = [1,5,8,9,7,6,6,8,0,1,2,3]


def solution(A):
    A.sort()
    
    seq_list = []
    
    for each in A:
        if each == A[0]:
            seq_list.append(each)
        elif each == seq_list[-1] + 1:
            seq_list.append(each)
        elif each == seq_list[-1] and each != A[-1]:
            pass
        elif each == seq_list[-1] and each == A[-1]:
            answer = each + 1
        elif each * -1 == abs(each):
            answer = 1
        else:
            answer = seq_list[-1]+1
            
    if len(seq_list) == len(A):
        answer = seq_list[-1]+1
        
        
    return answer
    
    # write your code in Python 3.6
    pass

In [0]:
A = [1,5,8,9,7,6,6,8,0,1,2,3]



import numpy as np

def solution(A):
    A.sort()
    np.unique(A)

    print(A)
#     seq_list = []
    
#     for each in A:
#         if each == A[0]:
#             seq_list.append(each)
#         elif each == seq_list[-1] + 1:
#             seq_list.append(each)

## Codility Binary Gap Problem
A binary gap within a positive integer N is any maximal sequence of consecutive zeros that is surrounded by ones at both ends in the binary representation of N.

For example, number 9 has binary representation 1001 and contains a binary gap of length 2. The number 529 has binary representation 1000010001 and contains two binary gaps: one of length 4 and one of length 3. The number 20 has binary representation 10100 and contains one binary gap of length 1. The number 15 has binary representation 1111 and has no binary gaps. The number 32 has binary representation 100000 and has no binary gaps.

Write a function:

def solution(N)

that, given a positive integer N, returns the length of its longest binary gap. The function should return 0 if N doesn't contain a binary gap.

For example, given N = 1041 the function should return 5, because N has binary representation 10000010001 and so its longest binary gap is of length 5. Given N = 32 the function should return 0, because N has binary representation '100000' and thus no binary gaps.

Write an efficient algorithm for the following assumptions:

N is an integer within the range [1..2,147,483,647].
Copyright 2009â€“2019 by Codility Limited. All Rights Reserved. Unauthoriz

In [0]:
##Binary gap problem 100%


N= 1041
def solution(N):
    # write your code in Python 3.6
    bin_1 = "{0:b}".format(N)
    
    count = 0
    count_list = []
    print (type(bin_1))
    split = []
    
    if bin_1[0] == bin_1[-1]:
        if '010' in bin_1:
            split = bin_1.split('01')
            
        elif '010' not in bin_1:
                zero_count = bin_1.count('0') 
                return zero_count
            
    elif bin_1[0] != bin_1[-1]:
        if '010' in bin_1:
            split = bin_1.split('01')
            del split[-1]
               
    else:
          return 0
        
    if not split:
        return 0
    else:
        for each in split:
            zero_count = each.count('0')
            count_list.append(zero_count)
        
    if not count_list:
        return 0
    else:
        return max(count_list)+1          
    
    

solution(N)

<class 'str'>

5

In [0]:
4
str(4)

'4'

## Codility Odd Occurances Problem

A non-empty array A consisting of N integers is given. The array contains an odd number of elements, and each element of the array can be paired with another element that has the same value, except for one element that is left unpaired.

For example, in array A such that:

  A[0] = 9  A[1] = 3  A[2] = 9
  A[3] = 3  A[4] = 9  A[5] = 7
  A[6] = 9
the elements at indexes 0 and 2 have value 9,
the elements at indexes 1 and 3 have value 3,
the elements at indexes 4 and 6 have value 9,
the element at index 5 has value 7 and is unpaired.
Write a function:

def solution(A)

that, given an array A consisting of N integers fulfilling the above conditions, returns the value of the unpaired element.

For example, given array A such that:

  A[0] = 9  A[1] = 3  A[2] = 9
  A[3] = 3  A[4] = 9  A[5] = 7
  A[6] = 9
the function should return 7, as explained in the example above.

Write an efficient algorithm for the following assumptions:

N is an odd integer within the range [1..1,000,000];
each element of array A is an integer within the range [1..1,000,000,000];
all but one of the values in A occur an even number of times.

In [0]:
#Odd occurances 66%. Failed speed tests

A = np.array([[9, 3, 9, 3, 9, 7, 9]])

output = []
def match(A):

    i=0

    odd = []
    even = []
    
    for each in A:
        if each not in odd:
            odd.append(each)
            i+=1
            
        elif each in odd:
            even.append(each)
            odd.remove(each)
            i+=1
    answer = odd[0] +0
    return answer


match(A)

##Codility Cyclic Rotation

An array A consisting of N integers is given. Rotation of the array means that each element is shifted right by one index, and the last element of the array is moved to the first place. For example, the rotation of array A = [3, 8, 9, 7, 6] is [6, 3, 8, 9, 7] (elements are shifted right by one index and 6 is moved to the first place).

The goal is to rotate array A K times; that is, each element of A will be shifted to the right K times.

Write a function:

def solution(A, K)

that, given an array A consisting of N integers and an integer K, returns the array A rotated K times.

For example, given

    A = [3, 8, 9, 7, 6]
    K = 3
the function should return [9, 7, 6, 3, 8]. Three rotations were made:

    [3, 8, 9, 7, 6] -> [6, 3, 8, 9, 7]
    [6, 3, 8, 9, 7] -> [7, 6, 3, 8, 9]
    [7, 6, 3, 8, 9] -> [9, 7, 6, 3, 8]
For another example, given

    A = [0, 0, 0]
    K = 1
the function should return [0, 0, 0]

Given

    A = [1, 2, 3, 4]
    K = 4
the function should return [1, 2, 3, 4]

Assume that:

N and K are integers within the range [0..100];
each element of array A is an integer within the range [âˆ’1,000..1,000].
In your solution, focus on correctness. The performance of your solution will not be the focus of the assessment.

In [0]:
#Rearranging an array. 87% because I don't know what answer they are looking for in an empty array.

import numpy as np

A=list([])
K=2

def switcharoo(A,K):
    if not A:
        return 'empty array'
    for i in range(K):
        A.insert(0,A[-1])
        del A[-1]

    return A 

switcharoo(A,K)

##Codility Frog Jump

A small frog wants to get to the other side of the road. The frog is currently located at position X and wants to get to a position greater than or equal to Y. The small frog always jumps a fixed distance, D.

Count the minimal number of jumps that the small frog must perform to reach its target.

Write a function:

def solution(X, Y, D)

that, given three integers X, Y and D, returns the minimal number of jumps from position X to a position equal to or greater than Y.

For example, given:

  X = 10
  Y = 85
  D = 30
the function should return 3, because the frog will be positioned as follows:

after the first jump, at position 10 + 30 = 40
after the second jump, at position 10 + 30 + 30 = 70
after the third jump, at position 10 + 30 + 30 + 30 = 100
Write an efficient algorithm for the following assumptions:

X, Y and D are integers within the range [1..1,000,000,000];
X â‰¤ Y.

In [0]:
#Correct 100% 11mins!!!

import math

X=10
Y=10
D=30

def jumper(X,Y,D):
  
  k = (Y - X)/D
  return math.ceil(k)
  

jumper(X,Y,D)

0

##Codility PermMissing element problem

An array A consisting of N different integers is given. The array contains integers in the range [1..(N + 1)], which means that exactly one element is missing.

Your goal is to find that missing element.

Write a function:

def solution(A)

that, given an array A, returns the value of the missing element.

For example, given array A such that:

  A[0] = 2
  A[1] = 3
  A[2] = 1
  A[3] = 5
the function should return 4, as it is the missing element.

Write an efficient algorithm for the following assumptions:

N is an integer within the range [0..100,000];
the elements of A are all distinct;
each element of array A is an integer within the range [1..(N + 1)].

In [0]:
#100% YAY! 

A = [2,3,1,5, 7, 6, 15, 14, 12, 13, 11, 10, 9, 4]

def solution(A):
    A.sort()
    if not A:
      return 1
  
    else:
  
      complete_list = []
      for each in A:
        
        if each == A[0]:
          complete_list.append(each)
          if each != 1:# num 1 skipped
            answer =1
            break
          elif each == A[-1]: #if it is the only member of the array the answer is +1
            answer = each +1
            
        elif each == complete_list[-1] + 1: # if it is the next sequential member of the list
          complete_list.append(each)
          if each == A[-1]:
            answer = each+1
            
        elif each == complete_list[-1]: #if it is a repeat value, although the directions say it won't happen
          if each == A[-1]: # if it's a repeat  and the last and no answer has been achieved
            answer = each+1
          else: #if it's a repeat and not the last, just skip it
            pass
          
        else:
          answer = each - 1
          break

    return answer
      

solution(A)

8

A non-empty array A consisting of N integers is given. Array A represents numbers on a tape.

Any integer P, such that 0 < P < N, splits this tape into two non-empty parts: A[0], A[1], ..., A[P âˆ’ 1] and A[P], A[P + 1], ..., A[N âˆ’ 1].

The difference between the two parts is the value of: |(A[0] + A[1] + ... + A[P âˆ’ 1]) âˆ’ (A[P] + A[P + 1] + ... + A[N âˆ’ 1])|

In other words, it is the absolute difference between the sum of the first part and the sum of the second part.

For example, consider array A such that:

  A[0] = 3
  A[1] = 1
  A[2] = 2
  A[3] = 4
  A[4] = 3
We can split this tape in four places:

P = 1, difference = |3 âˆ’ 10| = 7
P = 2, difference = |4 âˆ’ 9| = 5
P = 3, difference = |6 âˆ’ 7| = 1
P = 4, difference = |10 âˆ’ 3| = 7
Write a function:

def solution(A)

that, given a non-empty array A of N integers, returns the minimal difference that can be achieved.

For example, given:

  A[0] = 3
  A[1] = 1
  A[2] = 2
  A[3] = 4
  A[4] = 3
the function should return 1, as explained above.

Write an efficient algorithm for the following assumptions:

N is an integer within the range [2..100,000];
each element of array A is an integer within the range [âˆ’1,000..1,000].

In [0]:
# 53% too slow

A= [3,1,2,4,3]



def solution(A):
    i=1
    N = len(A)
    summed = []
    for each in A:
      while i < N:
        summed.append(abs(sum(A[0:i])-sum(A[i:])))
        i+=1
    
    return min(summed)
    
solution(A)

1

In [0]:
A= [0,1, 1, 7]



def solution(A):
    i=1
    N = len(A)
    summed = []
    while i < N:
      y= list(map(lambda each: (abs(sum(A[0:i])-sum(A[i:]))), i+=1, A))
      summed.append(y)
      i+=1
    
    return min(summed)
    
solution(A)

SyntaxError: ignored

In [0]:
# Also too slow 53%

A= [3,1,2,4,3]



def solution(A):
    i=1
    N = len(A)
    summed = []
    
    while i<N:
      y = (abs(sum(A[0:i])-sum(A[i:])))
      i+=1
      summed.append(y)
      
    return min(summed)
    
solution(A)

1

In [0]:
#playing with lambda

x = [2, 3, 4, 5, 6]
y = []
for v in x :
  y += [v * 5]

print (y)

y = list(map(lambda each: each * 5, x))
print (y)

y = list(map(lambda each : each * 5, filter(lambda u : u % 2, each)))
print(y)

[10, 15, 20, 25, 30]
[10, 15, 20, 25, 30]
[15, 25]

A non-empty array A consisting of N integers is given.

A permutation is a sequence containing each element from 1 to N once, and only once.

For example, array A such that:

    A[0] = 4
    A[1] = 1
    A[2] = 3
    A[3] = 2
is a permutation, but array A such that:

    A[0] = 4
    A[1] = 1
    A[2] = 3
is not a permutation, because value 2 is missing.

The goal is to check whether array A is a permutation.

Write a function:

def solution(A)

that, given an array A, returns 1 if array A is a permutation and 0 if it is not.

For example, given array A such that:

    A[0] = 4
    A[1] = 1
    A[2] = 3
    A[3] = 2
the function should return 1.

Given array A such that:

    A[0] = 4
    A[1] = 1
    A[2] = 3
the function should return 0.

Write an efficient algorithm for the following assumptions:

N is an integer within the range [1..100,000];
each element of array A is an integer within the range [1..1,000,000,000].

In [0]:
#Big O out the window
A= [1, 2, 3, 5]

def solution(A):
  A.sort()
  
  answer = [0 for x in A if len(A) == 1 and x !=1]
  answer = [1 for x in A if len(A) == 1 and x == 1]
  
  nums = []
  nope = []
  
  if len(A) > 1:
    for each in A:
      if each == A[0]:
        nums.append(each)
      elif each == nums[-1]+1:
        nums.append(each)
      else:
        nope.append(each)
        break
        
  if len(nope) >=1:
    answer = 0
  else:
    answer = 1
    
  return answer

solution(A)

0

In [0]:
#100% on first submission. Took 73 mins but daaamnnnn

A= [2, 4, 3, 5, 1]

def solution(A):
    A.sort()
  
    answer = [0 for x in A if len(A) == 1 and x !=1]
    answer = [1 for x in A if len(A) == 1 and x == 1]
  
    nums = []
    nope = []
  
    nums.append(A[0])
    
     
    A_new = A[1:]
      
    if len(A) > 1:
      [nums.append(each) if each == nums[-1]+1 else nope.append(each) for each in A_new ]

    if len(nope) >=1:
      answer = 0
    else:
      answer = 1
    
    if A[0] !=1:
      answer = 0
      
    return answer

solution(A)

1

A small frog wants to get to the other side of a river. The frog is initially located on one bank of the river (position 0) and wants to get to the opposite bank (position X+1). Leaves fall from a tree onto the surface of the river.

You are given an array A consisting of N integers representing the falling leaves. A[K] represents the position where one leaf falls at time K, measured in seconds.

The goal is to find the earliest time when the frog can jump to the other side of the river. The frog can cross only when leaves appear at every position across the river from 1 to X (that is, we want to find the earliest moment when all the positions from 1 to X are covered by leaves). You may assume that the speed of the current in the river is negligibly small, i.e. the leaves do not change their positions once they fall in the river.

For example, you are given integer X = 5 and array A such that:

  A[0] = 1
  A[1] = 3
  A[2] = 1
  A[3] = 4
  A[4] = 2
  A[5] = 3
  A[6] = 5
  A[7] = 4
In second 6, a leaf falls into position 5. This is the earliest time when leaves appear in every position across the river.

Write a function:

def solution (X,A)

that, given a non-empty array A consisting of N integers and integer X, returns the earliest time when the frog can jump to the other side of the river.

If the frog is never able to jump to the other side of the river, the function should return âˆ’1.

For example, given X = 5 and array A such that:

  A[0] = 1
  A[1] = 3
  A[2] = 1
  A[3] = 4
  A[4] = 2
  A[5] = 3
  A[6] = 5
  A[7] = 4
the function should return 6, as explained above.

Write an efficient algorithm for the following assumptions:

N and X are integers within the range [1..100,000];
each element of array A is an integer within the range [1..X].

In [0]:
#with for loops

import time
t0=time.time()

A = [1,3,1,4,2,3, 5,4, 5]
X=5
def solution (X,A):
  
    nums_list = []
    nums_list.append(A[0])
#     for each in A:
      
      
    if each not in nums_list for each in A:
      nums_list.append(each)
    elif each in nums_list for each in A:
      pass
    else:
      pass
    print(nums_list)
      
    if len(nums_list) == X:
      return A.index(nums_list[-1])
    else:
      return -1

    
solution(X,A)

t1=time.time()

print(t1-t0)

SyntaxError: ignored

In [0]:
#54% too slow

A = [1,3,1,4,2,3,4,]
X=5
def solution (X,A):
  

    nums_list = []
    nums_list.append(A[0])
    
    
    for each in A:
      if each not in nums_list:
        nums_list.append(each)
      elif each in nums_list:
        pass
      else:
        pass
       
    if len(nums_list) == X:
      return A.index(nums_list[-1])
    else:
      return -1
    
solution(X,A)

[1]

-1

A non-empty array A consisting of N integers is given. The consecutive elements of array A represent consecutive cars on a road.

Array A contains only 0s and/or 1s:

0 represents a car traveling east,
1 represents a car traveling west.
The goal is to count passing cars. We say that a pair of cars (P, Q), where 0 â‰¤ P < Q < N, is passing when P is traveling to the east and Q is traveling to the west.

For example, consider array A such that:

  A[0] = 0
  A[1] = 1
  A[2] = 0
  A[3] = 1
  A[4] = 0
We have five pairs of passing cars: (0, 1), (0, 3), (0, 4), (2, 3), (2, 4).

Write a function:

def solution(A)

that, given a non-empty array A of N integers, returns the number of pairs of passing cars.

The function should return âˆ’1 if the number of pairs of passing cars exceeds 1,000,000,000.

For example, given:

  A[0] = 0
  A[1] = 1
  A[2] = 0
  A[3] = 1
  A[4] = 1
the function should return 5, as explained above.

Write an efficient algorithm for the following assumptions:

N is an integer within the range [1..100,000];
each element of array A is an integer that can have one of the following values: 0, 1.

In [0]:
def solution (A):
    for each in A:
      if each == 0:
        one_count += 1

SyntaxError: ignored

Write a function:

def solution(A, B, K)

that, given three integers A, B and K, returns the number of integers within the range [A..B] that are divisible by K, i.e.:

{ i : A â‰¤ i â‰¤ B, i mod K = 0 }

For example, for A = 6, B = 11 and K = 2, your function should return 3, because there are three numbers divisible by 2 within the range [6..11], namely 6, 8 and 10.

Write an efficient algorithm for the following assumptions:

A and B are integers within the range [0..2,000,000,000];
K is an integer within the range [1..2,000,000,000];
A â‰¤ B.

In [0]:


def solution (A,B,K):
    count = 0
    for i in range (A,B):
      if i % K == 0:
        count += 1
        
    return count
        
solution(6,11,2)

3

In [0]:

def solution (A,B,K):
    count = 0
    
   
    for i in range (A,B):
      if i % K == 0:
        count += 1
        
    return count

In [0]:
N=-1600
#What I submitted
  
def solution(N):
    i=1
    N_string = str(N)
    
    if N==0:
      return 50
  
    for each in range(len(N_string)):
      #negatives
      if N_string[0]=='-' and int(N_string[i])<5:
        i+=1
        pass
        
      elif N_string[0]=='-' and int(N_string[i])>5:
        index = i
        
      #positives
      elif N_string[0]!='-' and int(N_string[i-1])<5:
        index = i
        
      elif N_string[0]!='-' and int(N_string[i-1])>5:
        i+=1
        pass
        

        
      else:
        index = N_list[-1]
        
      N_list = list(N_string)
      N_list.insert(index,5)
      
      string = [str(i) for i in N_list] 
      integer = res = int("".join(string)) 
  
      return integer
      
solution(N)

a

UnboundLocalError: ignored

In [0]:
#Correct answer I think for actual test
N=610


def solution(N):
    i=0
    N_string = str(N)     

    if N==0:
      return 50
    
    N_list = []
    P_list = []
    
    if N_string[0]== '-':
      
      [N_list.append(int(each)) for each in N_string[1:]]
      
    else:
      [P_list.append(int(each)) for each in N_string]
      
    print(N_list)   
    
    for each in N_list:
      if int(each) <5: #and each == N_list[-1]:
        index = N_list[-1]
        N_list.insert(index,5)
        
      
      elif int(each) <5 and not N_list[-1]:
        i+=1
        #N_list.append(each)
          
          
      elif int(each)>5:
        index = i
        N_list.insert(index,5)   
        
      else:
        i+=1
        pass
#     print ('list', N_list)    

      string = [str(x) for x in N_list] 
      ans = int("".join(string))   
      integer = ans*-1

      return integer
        
      i=0    
      
    for each in P_list:
      if int(each) >5: #and each == N_list[-1]:
        index = P_list[-1]
        P_list.insert(index,5)
        
      
      elif int(each) >5 and not N_list[-1]:
        i+=1
        #N_list.append(each)
          
          
      elif int(each)<5:
        index = i
        P_list.insert(index,5)   
        
      else:
        i+=1
        pass
#     print ('list', N_list)    

      string = [str(x) for x in P_list] 
      ans = int("".join(string))   
      integer = ans

      return integer
          
solution(N)

[]

5610

In [0]:
# N = 100

    if len(A) > 1:
      [nums.append(each) if each == nums[-1]+1 else nope.append(each) for each in A_new ]    
      
def solution (N):
  
    if N<0:
      []

In [0]:
#ROC answer

def solution(X, Y):
    
    i=0
    N=len(X)
    area_list = []
    
    while i < N-1:
        area = ((Y[i] + Y[i+1])/2) * (X[i+1]-X[i])
        area_list.append(area)
        i+=1
        
    return sum(area_list)
            

    pass

Codility GenomicRangeQuery:

A DNA sequence can be represented as a string consisting of the letters A, C, G and T, which correspond to the types of successive nucleotides in the sequence. Each nucleotide has an impact factor, which is an integer. Nucleotides of types A, C, G and T have impact factors of 1, 2, 3 and 4, respectively. You are going to answer several queries of the form: What is the minimal impact factor of nucleotides contained in a particular part of the given DNA sequence?

The DNA sequence is given as a non-empty string S = S[0]S[1]...S[N-1] consisting of N characters. There are M queries, which are given in non-empty arrays P and Q, each consisting of M integers. The K-th query (0 â‰¤ K < M) requires you to find the minimal impact factor of nucleotides contained in the DNA sequence between positions P[K] and Q[K] (inclusive).

For example, consider string S = CAGCCTA and arrays P, Q such that:

    P[0] = 2    Q[0] = 4
    P[1] = 5    Q[1] = 5
    P[2] = 0    Q[2] = 6
The answers to these M = 3 queries are as follows:

The part of the DNA between positions 2 and 4 contains nucleotides G and C (twice), whose impact factors are 3 and 2 respectively, so the answer is 2.
The part between positions 5 and 5 contains a single nucleotide T, whose impact factor is 4, so the answer is 4.
The part between positions 0 and 6 (the whole string) contains all nucleotides, in particular nucleotide A whose impact factor is 1, so the answer is 1.
Write a function:

def solution(S,P,Q)

that, given a non-empty string S consisting of N characters and two non-empty arrays P and Q consisting of M integers, returns an array consisting of M integers specifying the consecutive answers to all queries.

Result array should be returned as an array of integers.

For example, given the string S = CAGCCTA and arrays P, Q such that:

    P[0] = 2    Q[0] = 4
    P[1] = 5    Q[1] = 5
    P[2] = 0    Q[2] = 6
the function should return the values [2, 4, 1], as explained above.

Write an efficient algorithm for the following assumptions:

N is an integer within the range [1..100,000];
M is an integer within the range [1..50,000];
each element of arrays P, Q is an integer within the range [0..N âˆ’ 1];
P[K] â‰¤ Q[K], where 0 â‰¤ K < M;
string S consists only of upper-case English letters A, C, G, T.

In [0]:
#Not sure why this is wrong. 37% correct

S = 'AGGGGGG'

P = [0]
Q = [6]

def solution(S, P, Q):

    num_string = []

    for each in S:
      if each == 'A':
        num_string.append(1)
      elif each == 'C':
        num_string.append(2)
      elif each == 'G':
        num_string.append(3)
      elif each == 'T':
        num_string.append(4)
        
    
    
    i=0
      
    answer = []
    
   
    while i<len(P):
      string_range = (num_string[P[i]],num_string[Q[i]])
      answer.append(min(string_range))
      i+=1

          
    return answer

  
solution(S,P,Q)

[1]

##Codility

A non-empty array A consisting of N integers is given. The product of triplet (P, Q, R) equates to A[P] * A[Q] * A[R] (0 â‰¤ P < Q < R < N).

For example, array A such that:

  A[0] = -3
  A[1] = 1
  A[2] = 2
  A[3] = -2
  A[4] = 5
  A[5] = 6
contains the following example triplets:

(0, 1, 2), product is âˆ’3 * 1 * 2 = âˆ’6
(1, 2, 4), product is 1 * 2 * 5 = 10
(2, 4, 5), product is 2 * 5 * 6 = 60
Your goal is to find the maximal product of any triplet.

Write a function:

def solution(A)

that, given a non-empty array A, returns the value of the maximal product of any triplet.

For example, given array A such that:

  A[0] = -3
  A[1] = 1
  A[2] = 2
  A[3] = -2
  A[4] = 5
  A[5] = 6
the function should return 60, as the product of triplet (2, 4, 5) is maximal.

Write an efficient algorithm for the following assumptions:

N is an integer within the range [3..100,000];
each element of array A is an integer within the range [âˆ’1,000..1,000].

In [0]:
A = [1,4,-7,-2]

def solution(A):
    abs_list = []
    for each in A:
      abs_list.append(abs(each))
    
    max_num = max(abs_list)
    
    print(max_num)
solution(A)

7

In [0]:
A = [8, 3, 0]

def solution(A):
    A.sort()
    
    min_list = A[:2]
    max_list = A[-3:]
    
    negs= min_list[0]*min_list[1]*max_list[-1]
    pos = max_list[0]*max_list[1]*max_list[2]
  
    if negs > pos:
      return negs
    else:
      return pos

solution(A)

0

##Codility 75% fails time tests

Write a function

def solution(A)

that, given an array A consisting of N integers, returns the number of distinct values in array A.

For example, given array A consisting of six elements such that:

 A[0] = 2    A[1] = 1    A[2] = 1
 A[3] = 2    A[4] = 3    A[5] = 1
the function should return 3, because there are 3 distinct values appearing in array A, namely 1, 2 and 3.

Write an efficient algorithm for the following assumptions:

N is an integer within the range [0..100,000];
each element of array A is an integer within the range [âˆ’1,000,000..1,000,000].

In [0]:
A = []

def solution(A):
  

  unique = []
  
  for x in A:
    if x not in unique:
      unique.append(x)
      
  if len(A) == 0:
    return 0
      
  return len(unique)


solution(A)

0

An array A consisting of N integers is given. A triplet (P, Q, R) is triangular if 0 â‰¤ P < Q < R < N and:

A[P] + A[Q] > A[R],
A[Q] + A[R] > A[P],
A[R] + A[P] > A[Q].
For example, consider array A such that:

  A[0] = 10    A[1] = 2    A[2] = 5
  A[3] = 1     A[4] = 8    A[5] = 20
Triplet (0, 2, 4) is triangular.

Write a function:

def solution(A)

that, given an array A consisting of N integers, returns 1 if there exists a triangular triplet for this array and returns 0 otherwise.

For example, given array A such that:

  A[0] = 10    A[1] = 2    A[2] = 5
  A[3] = 1     A[4] = 8    A[5] = 20
the function should return 1, as explained above. Given array A such that:

  A[0] = 10    A[1] = 50    A[2] = 5
  A[3] = 1
the function should return 0.

Write an efficient algorithm for the following assumptions:

N is an integer within the range [0..100,000];
each element of array A is an integer within the range [âˆ’2,147,483,648..2,147,483,647].

In [0]:
A= [10,2,5,1,8,20]

#A= [10, 5, 50]
def solution(A):
    
  y_range = A[1:]
  z_range = A[2:]
  
  for x in A:
    for y in y_range:
      for z in z_range:
        print(x,y,z)
        if x +y > z and x+z > y and z+y > x and x!=y!=z:
          return 1
        else:
          return 0

#           else:
#             return (x,y,z)
        


    
    # write your code in Python 3.6

  
solution(A)

TypeError: ignored

Given an unsorted array of integers, find the smallest number in the array, the largest number in the array, and the smallest number between the two array bounds that is not in the array.

For instance, given the array [-1, 4, 5, -23, 24], the smallest number is -23, the largest number is 24, and the smallest number between the array bounds is -22. You may assume the input is well-formed.

You solution should return an array [smallest, minimumAbsent, largest]

The smallest integer should be the integer from the array with the lowest value.

The largest integer should be the integer from the array with the highest value.

The minimumAbsent is the smallest number between the largest and the smallest number that is not in the array.

In [0]:
A= [2, -4, 8, -5, 9, 7]
def solution(A):
    A.sort()
    
    minimum = min(A)
    maximum = max(A)
    absent = []
    range_A = range(minimum, maximum)
    
    for each in range_A:
      if each in A:
        pass
      else:
        absent.append(each)
        list_A = []
    list_A.append(minimum)
    list_A.append(min(absent))
    list_A.append(maximum)
    return (list_A)
  
  
solution (A)

[-5, -3, 9]

In [0]:
#Someone else's answer that is interesting. I have not seen 'next' used

def minMinMax(arr):
    s, mi, ma = set(arr), min(arr), max(arr)
    return [mi, next(x for x in range(mi+1, ma) if x not in s), ma]

In [0]:
# Code Wars
## Kata: Reversed sequence

#Get the number n (n>0) to return the reversed sequence from n to 1.

#Example : n=5 >> [5,4,3,2,1]

In [0]:
import numpy as np
import pandas as pd

n=(5)

range_l = list(range(n))


new_list = []
i=1
for each in range_l:
  new_list.append(each+1)

r = list(reversed(new_list))

# A much better answer:
#def reverseseq(n):
#    return list(range(n, 0, -1))

[]

In [19]:
#Count the number of divisors of a positive integer n.

#Random tests go up to n = 500000.

# divisors(4)  = 3  # 1, 2, 4
# divisors(5)  = 2  # 1, 5
# divisors(12) = 6  # 1, 2, 3, 4, 6, 12
# divisors(30) = 8  # 1, 2, 3, 5, 6, 10, 15, 30


def divisors(n):
  div = []
  a = n+1
  count =0
  for each in range(1, a):
    if n%each==0:
      div.append(each)
      count +=1
    else:
      pass
     
  return count

divisors(30)


#not mine:
#def divisors(n):
#    return  len([l_div for l_div in range(1, n + 1) if n % l_div == 0]);

8